# Development configuration for MockForge
# This configuration is optimized for development with permissive settings

# HTTP server configuration
http:
  port: 3000
  host: "127.0.0.1"
  openapi_spec: "examples/openapi-demo.json"  # Path to OpenAPI spec file
  cors_enabled: true
  request_timeout_secs: 30
  # Lenient validation in development
  request_validation: "warn"   # off|warn|enforce
  aggregate_validation_errors: true
  validate_responses: true     # warn-only logging
  response_template_expand: true  # Enable template expansion
  skip_admin_validation: true

# WebSocket server configuration
websocket:
  port: 3001
  host: "127.0.0.1"
  replay_file: "examples/ws-demo.jsonl"
  connection_timeout_secs: 300

# gRPC server configuration
grpc:
  port: 50051
  host: "127.0.0.1"

# Admin UI configuration (enabled in dev)
admin:
  enabled: true
  port: 9080
  host: "127.0.0.1"
  auth_required: false
  mount_path: null
  api_enabled: true

# Core MockForge configuration
core:
  latency_enabled: true
  failures_enabled: true
  # Higher latency in dev to simulate real conditions
  default_latency:
    base_ms: 100
    jitter_ms: 50
    distribution: "normal"
    std_dev_ms: 25.0
    min_ms: 20
    max_ms: 1000

# Proxy configuration to access firewall-blocked APIs
proxy:
  enabled: true
  upstream_url: "https://api.external-service.com"  # Default upstream URL for proxy
  timeout_seconds: 30
  prefix: "/external-api"  # Use /external-api prefix to distinguish proxied requests
  passthrough_by_default: false  # Only proxy requests with explicit proxy rules
  forward_headers:
    - "authorization"
    - "content-type"
    - "user-agent"
    - "x-request-id"
    - "x-api-key"
  additional_headers:
    "X-Proxy-Source": "mockforge-dev"
    "X-Proxy-Version": "1.0"

  # Per-route proxy rules for specific firewall-blocked APIs
  rules:
    - pattern: "/external-api/weather/*"  # Matches /external-api/weather/v1/forecast etc.
      upstream_url: "https://api.openweathermap.org"
      enabled: true
    - pattern: "/external-api/maps/*"     # Matches /external-api/maps/directions etc.
      upstream_url: "https://maps.googleapis.com"
      enabled: true
    - pattern: "/external-api/social/*"   # Matches /external-api/social/posts etc.
      upstream_url: "https://graph.facebook.com"
      enabled: true
    - pattern: "/external-api/payment/*"  # Matches /external-api/payment/process etc.
      upstream_url: "https://api.stripe.com"
      enabled: true
    - pattern: "/external-api/analytics/*" # Matches /external-api/analytics/track etc.
      upstream_url: "https://api.mixpanel.com"
      enabled: true

logging:
  level: "debug"  # More verbose logging in dev
  json_format: false
  file_path: "logs/mockforge-dev.log"
  max_file_size_mb: 10
  max_files: 5
