# Demo configuration using example files
# This configuration demonstrates how to run MockForge with the provided examples

# HTTP server configuration
http:
  port: 3000
  host: "127.0.0.1"
  openapi_spec: "examples/openapi-demo.json"  # Path to OpenAPI spec file
  cors_enabled: true
  request_timeout_secs: 30  # Required field for HTTP configuration
  request_validation: "enforce"
  aggregate_validation_errors: true
  validate_responses: false
  response_template_expand: true  # Enable template expansion for {{now}}, {{uuid}}, etc.
  skip_admin_validation: true

# WebSocket server configuration
websocket:
  port: 3001
  host: "127.0.0.1"
  replay_file: "examples/ws-demo.jsonl"  # Path to WebSocket replay file
  connection_timeout_secs: 300

# gRPC server configuration (requires proto files)
grpc:
  port: 50051
  host: "127.0.0.1"

# Admin UI configuration
admin:
  enabled: true
  port: 9080
  host: "127.0.0.1"
  api_enabled: true

# Core MockForge configuration
core:
  latency_enabled: true
  failures_enabled: false
