apiVersion: v1
kind: ServiceAccount
metadata:
  name: mockforge
  labels:
    app: mockforge

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mockforge
  labels:
    app: mockforge
rules:
# Allow reading ConfigMaps
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
# Allow reading Secrets
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
# Allow reading own pod info
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mockforge
  labels:
    app: mockforge
subjects:
- kind: ServiceAccount
  name: mockforge
roleRef:
  kind: Role
  name: mockforge
  apiGroup: rbac.authorization.k8s.io
