apiVersion: v1
entries:
  mockforge:
  - apiVersion: v2
    appVersion: 0.3.128
    created: "2026-05-09T22:07:15.985776385Z"
    description: A Helm chart for MockForge - Advanced API mocking and chaos engineering
      platform
    digest: 46db4ca2ec86497b01e945f2e1da0c7c08b1cacc1595c9804abdd08c8ca9d8ae
    home: https://mockforge.dev
    icon: https://mockforge.dev/logo.png
    keywords:
    - mockforge
    - api
    - mocking
    - chaos-engineering
    - testing
    maintainers:
    - email: team@mockforge.dev
      name: MockForge Team
    name: mockforge
    sources:
    - https://github.com/SaaSy-Solutions/mockforge
    type: application
    urls:
    - https://SaaSy-Solutions.github.io/mockforge/charts/mockforge-0.3.128.tgz
    version: 0.3.128
  - apiVersion: v2
    appVersion: 0.3.127
    created: "2026-05-09T22:07:15.984210905Z"
    description: A Helm chart for MockForge - Advanced API mocking and chaos engineering
      platform
    digest: 8369dc5fcbd59a9ea81e75921b41d212ed5575e388c0d4ead7cab957bb3457cf
    home: https://mockforge.dev
    icon: https://mockforge.dev/logo.png
    keywords:
    - mockforge
    - api
    - mocking
    - chaos-engineering
    - testing
    maintainers:
    - email: team@mockforge.dev
      name: MockForge Team
    name: mockforge
    sources:
    - https://github.com/SaaSy-Solutions/mockforge
    type: application
    urls:
    - https://SaaSy-Solutions.github.io/mockforge/charts/mockforge-0.3.127.tgz
    version: 0.3.127
  - apiVersion: v2
    appVersion: 0.3.125
    created: "2026-05-09T22:07:15.983463983Z"
    description: A Helm chart for MockForge - Advanced API mocking and chaos engineering
      platform
    digest: 74911cdf8d3baa4665d8bf126f7bb834bdec083441b0e59bb529477684ab5d28
    home: https://mockforge.dev
    icon: https://mockforge.dev/logo.png
    keywords:
    - mockforge
    - api
    - mocking
    - chaos-engineering
    - testing
    maintainers:
    - email: team@mockforge.dev
      name: MockForge Team
    name: mockforge
    sources:
    - https://github.com/SaaSy-Solutions/mockforge
    type: application
    urls:
    - https://SaaSy-Solutions.github.io/mockforge/charts/mockforge-0.3.125.tgz
    version: 0.3.125
  - apiVersion: v2
    appVersion: 0.3.124
    created: "2026-05-09T22:07:15.982709205Z"
    description: A Helm chart for MockForge - Advanced API mocking and chaos engineering
      platform
    digest: 118ecc4551578e9270c6e3648e0dd3c8a1b02d359679198e60853c2af1fe0a18
    home: https://mockforge.dev
    icon: https://mockforge.dev/logo.png
    keywords:
    - mockforge
    - api
    - mocking
    - chaos-engineering
    - testing
    maintainers:
    - email: team@mockforge.dev
      name: MockForge Team
    name: mockforge
    sources:
    - https://github.com/SaaSy-Solutions/mockforge
    type: application
    urls:
    - https://SaaSy-Solutions.github.io/mockforge/charts/mockforge-0.3.124.tgz
    version: 0.3.124
  - apiVersion: v2
    appVersion: 0.3.123
    created: "2026-05-09T22:07:15.981933816Z"
    description: A Helm chart for MockForge - Advanced API mocking and chaos engineering
      platform
    digest: 59659eab86dfe563413d2a2aa230c75dda81a112513a32096820c6c3e69cf2b9
    home: https://mockforge.dev
    icon: https://mockforge.dev/logo.png
    keywords:
    - mockforge
    - api
    - mocking
    - chaos-engineering
    - testing
    maintainers:
    - email: team@mockforge.dev
      name: MockForge Team
    name: mockforge
    sources:
    - https://github.com/SaaSy-Solutions/mockforge
    type: application
    urls:
    - https://SaaSy-Solutions.github.io/mockforge/charts/mockforge-0.3.123.tgz
    version: 0.3.123
  - apiVersion: v2
    appVersion: 0.3.122
    created: "2026-05-09T22:07:15.981171583Z"
    description: A Helm chart for MockForge - Advanced API mocking and chaos engineering
      platform
    digest: 6fc5a16d04ba486df9f24a4f58a48caeb9f1c6c376e8dad33b1ce7f037d31bcc
    home: https://mockforge.dev
    icon: https://mockforge.dev/logo.png
    keywords:
    - mockforge
    - api
    - mocking
    - chaos-engineering
    - testing
    maintainers:
    - email: team@mockforge.dev
      name: MockForge Team
    name: mockforge
    sources:
    - https://github.com/SaaSy-Solutions/mockforge
    type: application
    urls:
    - https://SaaSy-Solutions.github.io/mockforge/charts/mockforge-0.3.122.tgz
    version: 0.3.122
  - apiVersion: v2
    appVersion: 0.3.121
    created: "2026-05-09T22:07:15.980408909Z"
    description: A Helm chart for MockForge - Advanced API mocking and chaos engineering
      platform
    digest: b73900d4c49e0fe5dfdcb3d0f17de2c9ccb43a4503cb45e0c54039750a68f275
    home: https://mockforge.dev
    icon: https://mockforge.dev/logo.png
    keywords:
    - mockforge
    - api
    - mocking
    - chaos-engineering
    - testing
    maintainers:
    - email: team@mockforge.dev
      name: MockForge Team
    name: mockforge
    sources:
    - https://github.com/SaaSy-Solutions/mockforge
    type: application
    urls:
    - https://SaaSy-Solutions.github.io/mockforge/charts/mockforge-0.3.121.tgz
    version: 0.3.121
  - apiVersion: v2
    appVersion: 0.3.120
    created: "2026-05-09T22:07:15.9796588Z"
    description: A Helm chart for MockForge - Advanced API mocking and chaos engineering
      platform
    digest: 799caf2397331871573a684402b20517c5aa0031b6a71bb3341470c1110426e6
    home: https://mockforge.dev
    icon: https://mockforge.dev/logo.png
    keywords:
    - mockforge
    - api
    - mocking
    - chaos-engineering
    - testing
    maintainers:
    - email: team@mockforge.dev
      name: MockForge Team
    name: mockforge
    sources:
    - https://github.com/SaaSy-Solutions/mockforge
    type: application
    urls:
    - https://SaaSy-Solutions.github.io/mockforge/charts/mockforge-0.3.120.tgz
    version: 0.3.120
  - apiVersion: v2
    appVersion: 0.3.119
    created: "2026-05-09T22:07:15.978903552Z"
    description: A Helm chart for MockForge - Advanced API mocking and chaos engineering
      platform
    digest: cc9c0f848a1a67b7acaaa7890c59746731cf7fce2fd1a4aea79343546381f313
    home: https://mockforge.dev
    icon: https://mockforge.dev/logo.png
    keywords:
    - mockforge
    - api
    - mocking
    - chaos-engineering
    - testing
    maintainers:
    - email: team@mockforge.dev
      name: MockForge Team
    name: mockforge
    sources:
    - https://github.com/SaaSy-Solutions/mockforge
    type: application
    urls:
    - https://SaaSy-Solutions.github.io/mockforge/charts/mockforge-0.3.119.tgz
    version: 0.3.119
  - apiVersion: v2
    appVersion: 0.3.118
    created: "2026-05-09T22:07:15.978155376Z"
    description: A Helm chart for MockForge - Advanced API mocking and chaos engineering
      platform
    digest: b57015c781bce1b2ca6aba727c499d60ea2b2a243582522c921b256c270afb06
    home: https://mockforge.dev
    icon: https://mockforge.dev/logo.png
    keywords:
    - mockforge
    - api
    - mocking
    - chaos-engineering
    - testing
    maintainers:
    - email: team@mockforge.dev
      name: MockForge Team
    name: mockforge
    sources:
    - https://github.com/mockforge/mockforge
    type: application
    urls:
    - https://SaaSy-Solutions.github.io/mockforge/charts/mockforge-0.3.118.tgz
    version: 0.3.118
  - apiVersion: v2
    appVersion: 0.3.117
    created: "2026-05-09T22:07:15.977352233Z"
    description: A Helm chart for MockForge - Advanced API mocking and chaos engineering
      platform
    digest: 26cc6abb5ef985010ee3cc29102c10b3065f0c759c70390f7f4028ce2524edc7
    home: https://mockforge.dev
    icon: https://mockforge.dev/logo.png
    keywords:
    - mockforge
    - api
    - mocking
    - chaos-engineering
    - testing
    maintainers:
    - email: team@mockforge.dev
      name: MockForge Team
    name: mockforge
    sources:
    - https://github.com/mockforge/mockforge
    type: application
    urls:
    - https://SaaSy-Solutions.github.io/mockforge/charts/mockforge-0.3.117.tgz
    version: 0.3.117
  - apiVersion: v2
    appVersion: 0.3.70
    created: "2026-05-09T22:07:15.989595735Z"
    description: A Helm chart for MockForge - Advanced API mocking and chaos engineering
      platform
    digest: 92efa1d7db9f8e3d5cfa47480713539295ed2ced6368cf00175bb36ef30a998f
    home: https://mockforge.dev
    icon: https://mockforge.dev/logo.png
    keywords:
    - mockforge
    - api
    - mocking
    - chaos-engineering
    - testing
    maintainers:
    - email: team@mockforge.dev
      name: MockForge Team
    name: mockforge
    sources:
    - https://github.com/mockforge/mockforge
    type: application
    urls:
    - https://SaaSy-Solutions.github.io/mockforge/charts/mockforge-0.3.70.tgz
    version: 0.3.70
  - apiVersion: v2
    appVersion: 0.3.65
    created: "2026-05-09T22:07:15.988826188Z"
    description: A Helm chart for MockForge - Advanced API mocking and chaos engineering
      platform
    digest: 2c2219d3240583029daebfcf67e4a89252e6b2edb564db2ea0f2e93b6022943c
    home: https://mockforge.dev
    icon: https://mockforge.dev/logo.png
    keywords:
    - mockforge
    - api
    - mocking
    - chaos-engineering
    - testing
    maintainers:
    - email: team@mockforge.dev
      name: MockForge Team
    name: mockforge
    sources:
    - https://github.com/mockforge/mockforge
    type: application
    urls:
    - https://SaaSy-Solutions.github.io/mockforge/charts/mockforge-0.3.65.tgz
    version: 0.3.65
  - apiVersion: v2
    appVersion: 0.3.64
    created: "2026-05-09T22:07:15.988100508Z"
    description: A Helm chart for MockForge - Advanced API mocking and chaos engineering
      platform
    digest: 966abaa60d7c697c8833ba86d5dce0cadae2086d845105b042bc09115e97344f
    home: https://mockforge.dev
    icon: https://mockforge.dev/logo.png
    keywords:
    - mockforge
    - api
    - mocking
    - chaos-engineering
    - testing
    maintainers:
    - email: team@mockforge.dev
      name: MockForge Team
    name: mockforge
    sources:
    - https://github.com/mockforge/mockforge
    type: application
    urls:
    - https://SaaSy-Solutions.github.io/mockforge/charts/mockforge-0.3.64.tgz
    version: 0.3.64
  - apiVersion: v2
    appVersion: 0.3.63
    created: "2026-05-09T22:07:15.987342753Z"
    description: A Helm chart for MockForge - Advanced API mocking and chaos engineering
      platform
    digest: 251d46e38a3c2663c527dc1a1c90246d6ac51e9594ea77e7759094e660903d20
    home: https://mockforge.dev
    icon: https://mockforge.dev/logo.png
    keywords:
    - mockforge
    - api
    - mocking
    - chaos-engineering
    - testing
    maintainers:
    - email: team@mockforge.dev
      name: MockForge Team
    name: mockforge
    sources:
    - https://github.com/mockforge/mockforge
    type: application
    urls:
    - https://SaaSy-Solutions.github.io/mockforge/charts/mockforge-0.3.63.tgz
    version: 0.3.63
  - apiVersion: v2
    appVersion: 0.3.62
    created: "2026-05-09T22:07:15.986563286Z"
    description: A Helm chart for MockForge - Advanced API mocking and chaos engineering
      platform
    digest: 8739c41e50dfbd0cf73d7be060f13fb61305a57ad0ee9cafb108303b57349b54
    home: https://mockforge.dev
    icon: https://mockforge.dev/logo.png
    keywords:
    - mockforge
    - api
    - mocking
    - chaos-engineering
    - testing
    maintainers:
    - email: team@mockforge.dev
      name: MockForge Team
    name: mockforge
    sources:
    - https://github.com/mockforge/mockforge
    type: application
    urls:
    - https://SaaSy-Solutions.github.io/mockforge/charts/mockforge-0.3.62.tgz
    version: 0.3.62
generated: "2026-05-09T22:07:15.976340605Z"
