[package]
name = "mockforge-plugin-{{plugin_name}}"
version = "0.1.0"
edition = "2021"
authors = ["{{author_name}} <{{author_email}}>"]
description = "{{plugin_description}}"
license = "MIT OR Apache-2.0"

[lib]
crate-type = ["cdylib"]  # Required for WebAssembly compilation

[dependencies]
# MockForge plugin core - provides traits and types
mockforge-plugin-core = { git = "https://github.com/mockforge/mockforge", branch = "main" }

# WebAssembly Interface Types
wit-bindgen = "0.34"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Async traits
async-trait = "0.1"

# Error handling
anyhow = "1"
thiserror = "2.0"

[dev-dependencies]
tokio = { version = "1.0", features = ["macros", "rt-multi-thread", "test-util"] }

[profile.release]
opt-level = "z"     # Optimize for size
lto = true          # Enable link-time optimization
codegen-units = 1   # Better optimization
strip = true        # Strip symbols
