[package]
name = "mockforge-smtp"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "SMTP mocking support for MockForge"
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/mockforge"
readme = "README.md"
keywords = ["smtp", "email", "mock", "testing", "api"]
categories = ["development-tools", "email"]

[dependencies]
# MockForge core
mockforge-core = "0.1.0"

# Standard workspace dependencies
tokio = { workspace = true, features = ["net", "io-util"] }
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }

# SMTP-specific dependencies
mail-parser = "0.9"
chrono = { workspace = true }
uuid = { workspace = true }
regex = { workspace = true }
tokio-rustls = "0.24"
rustls-pemfile = "1.0"
rustls = "0.21"

[dev-dependencies]
tokio = { workspace = true, features = ["test-util", "macros"] }
tempfile = "3.0"
criterion = { workspace = true }

[[bench]]
name = "smtp_benchmarks"
harness = false
