apiVersion: v1
kind: Service
metadata:
  name: {{ include "mockforge.fullname" . }}
  labels:
    {{- include "mockforge.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.http.port }}
    targetPort: http
    protocol: TCP
    name: http
  - port: {{ .Values.service.websocket.port }}
    targetPort: websocket
    protocol: TCP
    name: websocket
  - port: {{ .Values.service.grpc.port }}
    targetPort: grpc
    protocol: TCP
    name: grpc
  - port: {{ .Values.service.admin.port }}
    targetPort: admin
    protocol: TCP
    name: admin
  - port: {{ .Values.service.metrics.port }}
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    {{- include "mockforge.selectorLabels" . | nindent 4 }}
