//! SQLite implementation of [`RegistryStore`].
//!
//! This backend powers the single-tenant OSS admin server embedded in
//! `mockforge-ui`. It targets a subset of the domain — authentication,
//! users, organizations, API tokens, audit logs, settings — and returns
//! sensible empty defaults (or [`StoreError::NotFound`]) for SaaS-only
//! features like the plugin/template/scenario marketplace, SSO/SAML,
//! Stripe billing, hosted mocks, federations, and cloud workspaces.
//!
//! The migrations for this backend live in `../../migrations-sqlite/` and
//! are applied at connect time via [`SqliteRegistryStore::connect`].
//!
//! This is the Phase 2b skeleton — the struct, the connect/migrate entry
//! points, and a `RegistryStore` impl whose methods are generated stubs.
//! Follow-up commits will fill in real SQLite queries for the
//! OSS-essential paths (users, api tokens, orgs, audit logging).

#![cfg(feature = "sqlite")]

use async_trait::async_trait;
use chrono::{DateTime, Utc};
use sqlx::sqlite::{SqlitePool, SqlitePoolOptions};
use uuid::Uuid;

use super::{
    AdminAnalyticsSnapshot, ConversionFunnelSnapshot, OrgSettingRow, ProjectRow, RegistryStore,
    SubscriptionRow, UserSettingRow,
};
use crate::error::{StoreError, StoreResult};
use crate::models::api_token::{ApiToken, TokenScope};
use crate::models::audit_log::{AuditEventType, AuditLog};
use crate::models::cloud_fixture::CloudFixture;
use crate::models::cloud_service::CloudService;
use crate::models::cloud_workspace::Workspace as CloudWorkspace;
use crate::models::feature_usage::{FeatureType, FeatureUsage};
use crate::models::federation::Federation;
use crate::models::hosted_mock::{DeploymentStatus, HealthStatus, HostedMock};
use crate::models::org_template::OrgTemplate;
use crate::models::organization::{OrgMember, OrgRole, Organization, Plan};
use crate::models::plugin::{Plugin, PluginVersion};
use crate::models::review::Review;
use crate::models::saml_assertion::SAMLAssertionId;
use crate::models::scenario::Scenario;
use crate::models::scenario_review::ScenarioReview;
use crate::models::settings::OrgSetting;
use crate::models::sso::{SSOConfiguration, SSOProvider};
use crate::models::subscription::UsageCounter;
use crate::models::suspicious_activity::{SuspiciousActivity, SuspiciousActivityType};
use crate::models::template::{Template, TemplateCategory};
use crate::models::template_review::TemplateReview;
use crate::models::user::User;
use crate::models::verification_token::VerificationToken;
use crate::models::waitlist::WaitlistSubscriber;

/// SQLite-backed [`RegistryStore`] implementation for the OSS admin UI.
#[derive(Clone)]
pub struct SqliteRegistryStore {
    pool: SqlitePool,
}

impl SqliteRegistryStore {
    /// Wrap an existing [`SqlitePool`] in a registry store.
    pub fn new(pool: SqlitePool) -> Self {
        Self { pool }
    }

    /// Open (and create if missing) a SQLite database at the given URL and
    /// run the bundled OSS migrations.
    ///
    /// The URL must be in sqlx form, e.g. `sqlite://./mockforge.db` or
    /// `sqlite::memory:` for an in-process database.
    pub async fn connect(database_url: &str) -> StoreResult<Self> {
        let pool = SqlitePoolOptions::new().max_connections(5).connect(database_url).await?;
        let this = Self { pool };
        this.migrate().await?;
        Ok(this)
    }

    /// Run the bundled SQLite migrations (subset of the Postgres schema).
    pub async fn migrate(&self) -> StoreResult<()> {
        sqlx::migrate!("../mockforge-registry-server/migrations-sqlite")
            .run(&self.pool)
            .await
            .map_err(|e| StoreError::Hash(format!("migrate: {}", e)))?;
        Ok(())
    }

    /// Borrow the underlying pool. Exposed for tests and advanced wiring.
    pub fn pool(&self) -> &SqlitePool {
        &self.pool
    }
}

#[async_trait]
impl RegistryStore for SqliteRegistryStore {
    // Generated by /tmp/gen_sqlite_stub.py — do not edit by hand.
    // Contains 151 method stubs.

    #[allow(unused_variables)]
    async fn health_check(&self) -> StoreResult<()> {
        Ok(())
    }

    #[allow(unused_variables)]
    async fn create_api_token(
        &self,
        org_id: Uuid,
        user_id: Option<Uuid>,
        name: &str,
        scopes: &[TokenScope],
        expires_at: Option<DateTime<Utc>>,
    ) -> StoreResult<(String, ApiToken)> {
        Err(StoreError::Hash(
            "create_api_token: not yet implemented in SQLite backend".into(),
        ))
    }

    #[allow(unused_variables)]
    async fn find_api_token_by_id(&self, token_id: Uuid) -> StoreResult<Option<ApiToken>> {
        Ok(None)
    }

    #[allow(unused_variables)]
    async fn list_api_tokens_by_org(&self, org_id: Uuid) -> StoreResult<Vec<ApiToken>> {
        Ok(Vec::new())
    }

    #[allow(unused_variables)]
    async fn find_api_token_by_prefix(
        &self,
        org_id: Uuid,
        prefix: &str,
    ) -> StoreResult<Option<ApiToken>> {
        Ok(None)
    }

    #[allow(unused_variables)]
    async fn verify_api_token(&self, token: &str) -> StoreResult<Option<ApiToken>> {
        Ok(None)
    }

    #[allow(unused_variables)]
    async fn delete_api_token(&self, token_id: Uuid) -> StoreResult<()> {
        Ok(())
    }

    #[allow(unused_variables)]
    async fn rotate_api_token(
        &self,
        token_id: Uuid,
        new_name: Option<&str>,
        delete_old: bool,
    ) -> StoreResult<(String, ApiToken, Option<ApiToken>)> {
        Err(StoreError::Hash(
            "rotate_api_token: not yet implemented in SQLite backend".into(),
        ))
    }

    #[allow(unused_variables)]
    async fn find_api_tokens_needing_rotation(
        &self,
        org_id: Option<Uuid>,
        days_old: i64,
    ) -> StoreResult<Vec<ApiToken>> {
        Ok(Vec::new())
    }

    #[allow(unused_variables)]
    async fn get_org_setting(&self, org_id: Uuid, key: &str) -> StoreResult<Option<OrgSetting>> {
        Ok(None)
    }

    #[allow(unused_variables)]
    async fn set_org_setting(
        &self,
        org_id: Uuid,
        key: &str,
        value: serde_json::Value,
    ) -> StoreResult<OrgSetting> {
        Err(StoreError::NotFound)
    }

    #[allow(unused_variables)]
    async fn delete_org_setting(&self, org_id: Uuid, key: &str) -> StoreResult<()> {
        Ok(())
    }

    #[allow(unused_variables)]
    async fn create_organization(
        &self,
        name: &str,
        slug: &str,
        owner_id: Uuid,
        plan: Plan,
    ) -> StoreResult<Organization> {
        Err(StoreError::NotFound)
    }

    #[allow(unused_variables)]
    async fn find_organization_by_id(&self, org_id: Uuid) -> StoreResult<Option<Organization>> {
        Ok(None)
    }

    #[allow(unused_variables)]
    async fn find_organization_by_slug(&self, slug: &str) -> StoreResult<Option<Organization>> {
        Ok(None)
    }

    #[allow(unused_variables)]
    async fn list_organizations_by_user(&self, user_id: Uuid) -> StoreResult<Vec<Organization>> {
        Ok(Vec::new())
    }

    #[allow(unused_variables)]
    async fn update_organization_name(&self, org_id: Uuid, name: &str) -> StoreResult<()> {
        Ok(())
    }

    #[allow(unused_variables)]
    async fn update_organization_slug(&self, org_id: Uuid, slug: &str) -> StoreResult<()> {
        Ok(())
    }

    #[allow(unused_variables)]
    async fn update_organization_plan(&self, org_id: Uuid, plan: Plan) -> StoreResult<()> {
        Ok(())
    }

    #[allow(unused_variables)]
    async fn organization_has_active_subscription(&self, org_id: Uuid) -> StoreResult<bool> {
        Ok(false)
    }

    #[allow(unused_variables)]
    async fn delete_organization(&self, org_id: Uuid) -> StoreResult<()> {
        Ok(())
    }

    #[allow(unused_variables)]
    async fn create_org_member(
        &self,
        org_id: Uuid,
        user_id: Uuid,
        role: OrgRole,
    ) -> StoreResult<OrgMember> {
        Err(StoreError::NotFound)
    }

    #[allow(unused_variables)]
    async fn find_org_member(&self, org_id: Uuid, user_id: Uuid) -> StoreResult<Option<OrgMember>> {
        Ok(None)
    }

    #[allow(unused_variables)]
    async fn list_org_members(&self, org_id: Uuid) -> StoreResult<Vec<OrgMember>> {
        Ok(Vec::new())
    }

    #[allow(unused_variables)]
    async fn update_org_member_role(
        &self,
        org_id: Uuid,
        user_id: Uuid,
        role: OrgRole,
    ) -> StoreResult<()> {
        Ok(())
    }

    #[allow(unused_variables)]
    async fn delete_org_member(&self, org_id: Uuid, user_id: Uuid) -> StoreResult<()> {
        Ok(())
    }

    #[allow(unused_variables)]
    async fn record_audit_event(
        &self,
        org_id: Uuid,
        user_id: Option<Uuid>,
        event_type: AuditEventType,
        description: String,
        metadata: Option<serde_json::Value>,
        ip_address: Option<&str>,
        user_agent: Option<&str>,
    ) {
    }

    #[allow(unused_variables)]
    async fn list_audit_logs(
        &self,
        org_id: Uuid,
        limit: Option<i64>,
        offset: Option<i64>,
        event_type: Option<AuditEventType>,
    ) -> StoreResult<Vec<AuditLog>> {
        Ok(Vec::new())
    }

    #[allow(unused_variables)]
    async fn count_audit_logs(
        &self,
        org_id: Uuid,
        event_type: Option<AuditEventType>,
    ) -> StoreResult<i64> {
        Ok(0)
    }

    #[allow(unused_variables)]
    async fn record_feature_usage(
        &self,
        org_id: Uuid,
        user_id: Option<Uuid>,
        feature: FeatureType,
        metadata: Option<serde_json::Value>,
    ) {
    }

    #[allow(unused_variables)]
    async fn count_feature_usage_by_org(
        &self,
        org_id: Uuid,
        feature: FeatureType,
        days: i64,
    ) -> StoreResult<i64> {
        Ok(0)
    }

    #[allow(unused_variables)]
    async fn create_user(
        &self,
        username: &str,
        email: &str,
        password_hash: &str,
    ) -> StoreResult<User> {
        Err(StoreError::NotFound)
    }

    #[allow(unused_variables)]
    async fn find_user_by_id(&self, user_id: Uuid) -> StoreResult<Option<User>> {
        Ok(None)
    }

    #[allow(unused_variables)]
    async fn find_user_by_email(&self, email: &str) -> StoreResult<Option<User>> {
        Ok(None)
    }

    #[allow(unused_variables)]
    async fn find_user_by_username(&self, username: &str) -> StoreResult<Option<User>> {
        Ok(None)
    }

    #[allow(unused_variables)]
    async fn find_users_by_ids(&self, ids: &[Uuid]) -> StoreResult<Vec<User>> {
        Ok(Vec::new())
    }

    #[allow(unused_variables)]
    async fn set_user_api_token(&self, user_id: Uuid, token: &str) -> StoreResult<()> {
        Ok(())
    }

    #[allow(unused_variables)]
    async fn enable_user_2fa(
        &self,
        user_id: Uuid,
        secret: &str,
        backup_codes: &[String],
    ) -> StoreResult<()> {
        Ok(())
    }

    #[allow(unused_variables)]
    async fn disable_user_2fa(&self, user_id: Uuid) -> StoreResult<()> {
        Ok(())
    }

    #[allow(unused_variables)]
    async fn update_user_2fa_verified(&self, user_id: Uuid) -> StoreResult<()> {
        Ok(())
    }

    #[allow(unused_variables)]
    async fn remove_user_backup_code(&self, user_id: Uuid, code_index: usize) -> StoreResult<()> {
        Ok(())
    }

    #[allow(unused_variables)]
    async fn find_user_by_github_id(&self, github_id: &str) -> StoreResult<Option<User>> {
        Ok(None)
    }

    #[allow(unused_variables)]
    async fn find_user_by_google_id(&self, google_id: &str) -> StoreResult<Option<User>> {
        Ok(None)
    }

    #[allow(unused_variables)]
    async fn link_user_github_account(
        &self,
        user_id: Uuid,
        github_id: &str,
        avatar_url: Option<&str>,
    ) -> StoreResult<()> {
        Ok(())
    }

    #[allow(unused_variables)]
    async fn link_user_google_account(
        &self,
        user_id: Uuid,
        google_id: &str,
        avatar_url: Option<&str>,
    ) -> StoreResult<()> {
        Ok(())
    }

    #[allow(unused_variables)]
    async fn create_oauth_user(
        &self,
        username: &str,
        email: &str,
        password_hash: &str,
        auth_provider: &str,
        github_id: Option<&str>,
        google_id: Option<&str>,
        avatar_url: Option<&str>,
    ) -> StoreResult<User> {
        Err(StoreError::NotFound)
    }

    #[allow(unused_variables)]
    async fn get_or_create_personal_org(
        &self,
        user_id: Uuid,
        username: &str,
    ) -> StoreResult<Organization> {
        Err(StoreError::NotFound)
    }

    #[allow(unused_variables)]
    async fn update_user_password_hash(
        &self,
        user_id: Uuid,
        password_hash: &str,
    ) -> StoreResult<()> {
        Ok(())
    }

    #[allow(unused_variables)]
    async fn mark_user_verified(&self, user_id: Uuid) -> StoreResult<()> {
        Ok(())
    }

    #[allow(unused_variables)]
    async fn create_verification_token(&self, user_id: Uuid) -> StoreResult<VerificationToken> {
        Err(StoreError::NotFound)
    }

    #[allow(unused_variables)]
    async fn set_verification_token_expiry_hours(
        &self,
        token_id: Uuid,
        hours: i64,
    ) -> StoreResult<()> {
        Ok(())
    }

    #[allow(unused_variables)]
    async fn find_verification_token_by_token(
        &self,
        token: &str,
    ) -> StoreResult<Option<VerificationToken>> {
        Ok(None)
    }

    #[allow(unused_variables)]
    async fn mark_verification_token_used(&self, token_id: Uuid) -> StoreResult<()> {
        Ok(())
    }

    #[allow(unused_variables)]
    async fn record_suspicious_activity(
        &self,
        org_id: Option<Uuid>,
        user_id: Option<Uuid>,
        activity_type: SuspiciousActivityType,
        severity: &str,
        description: String,
        metadata: Option<serde_json::Value>,
        ip_address: Option<&str>,
        user_agent: Option<&str>,
    ) {
    }

    #[allow(unused_variables)]
    async fn create_federation(
        &self,
        org_id: Uuid,
        created_by: Uuid,
        name: &str,
        description: &str,
        services: &serde_json::Value,
    ) -> StoreResult<Federation> {
        Err(StoreError::NotFound)
    }

    #[allow(unused_variables)]
    async fn find_federation_by_id(&self, id: Uuid) -> StoreResult<Option<Federation>> {
        Ok(None)
    }

    #[allow(unused_variables)]
    async fn list_federations_by_org(&self, org_id: Uuid) -> StoreResult<Vec<Federation>> {
        Ok(Vec::new())
    }

    #[allow(unused_variables)]
    async fn update_federation(
        &self,
        id: Uuid,
        name: Option<&str>,
        description: Option<&str>,
        services: Option<&serde_json::Value>,
    ) -> StoreResult<Option<Federation>> {
        Ok(None)
    }

    #[allow(unused_variables)]
    async fn delete_federation(&self, id: Uuid) -> StoreResult<()> {
        Ok(())
    }

    #[allow(unused_variables)]
    async fn list_unresolved_suspicious_activities(
        &self,
        org_id: Option<Uuid>,
        user_id: Option<Uuid>,
        severity: Option<&str>,
        limit: Option<i64>,
    ) -> StoreResult<Vec<SuspiciousActivity>> {
        Ok(Vec::new())
    }

    #[allow(unused_variables)]
    async fn count_unresolved_suspicious_activities(&self, org_id: Uuid) -> StoreResult<i64> {
        Ok(0)
    }

    #[allow(unused_variables)]
    async fn resolve_suspicious_activity(
        &self,
        activity_id: Uuid,
        resolved_by: Uuid,
    ) -> StoreResult<()> {
        Ok(())
    }

    #[allow(unused_variables)]
    async fn create_cloud_workspace(
        &self,
        org_id: Uuid,
        created_by: Uuid,
        name: &str,
        description: &str,
    ) -> StoreResult<CloudWorkspace> {
        Err(StoreError::NotFound)
    }

    #[allow(unused_variables)]
    async fn find_cloud_workspace_by_id(&self, id: Uuid) -> StoreResult<Option<CloudWorkspace>> {
        Ok(None)
    }

    #[allow(unused_variables)]
    async fn list_cloud_workspaces_by_org(&self, org_id: Uuid) -> StoreResult<Vec<CloudWorkspace>> {
        Ok(Vec::new())
    }

    #[allow(unused_variables)]
    async fn update_cloud_workspace(
        &self,
        id: Uuid,
        name: Option<&str>,
        description: Option<&str>,
        is_active: Option<bool>,
        settings: Option<&serde_json::Value>,
    ) -> StoreResult<Option<CloudWorkspace>> {
        Ok(None)
    }

    #[allow(unused_variables)]
    async fn delete_cloud_workspace(&self, id: Uuid) -> StoreResult<()> {
        Ok(())
    }

    #[allow(unused_variables)]
    async fn create_cloud_service(
        &self,
        org_id: Uuid,
        created_by: Uuid,
        name: &str,
        description: &str,
        base_url: &str,
    ) -> StoreResult<CloudService> {
        Err(StoreError::NotFound)
    }

    #[allow(unused_variables)]
    async fn find_cloud_service_by_id(&self, id: Uuid) -> StoreResult<Option<CloudService>> {
        Ok(None)
    }

    #[allow(unused_variables)]
    async fn list_cloud_services_by_org(&self, org_id: Uuid) -> StoreResult<Vec<CloudService>> {
        Ok(Vec::new())
    }

    #[allow(unused_variables)]
    async fn update_cloud_service(
        &self,
        id: Uuid,
        name: Option<&str>,
        description: Option<&str>,
        base_url: Option<&str>,
        enabled: Option<bool>,
        tags: Option<&serde_json::Value>,
        routes: Option<&serde_json::Value>,
    ) -> StoreResult<Option<CloudService>> {
        Ok(None)
    }

    #[allow(unused_variables)]
    async fn delete_cloud_service(&self, id: Uuid) -> StoreResult<()> {
        Ok(())
    }

    #[allow(unused_variables)]
    async fn create_cloud_fixture(
        &self,
        org_id: Uuid,
        created_by: Uuid,
        name: &str,
        description: &str,
        path: &str,
        method: &str,
        content: Option<&serde_json::Value>,
    ) -> StoreResult<CloudFixture> {
        Err(StoreError::NotFound)
    }

    #[allow(unused_variables)]
    async fn find_cloud_fixture_by_id(&self, id: Uuid) -> StoreResult<Option<CloudFixture>> {
        Ok(None)
    }

    #[allow(unused_variables)]
    async fn list_cloud_fixtures_by_org(&self, org_id: Uuid) -> StoreResult<Vec<CloudFixture>> {
        Ok(Vec::new())
    }

    #[allow(unused_variables)]
    async fn update_cloud_fixture(
        &self,
        id: Uuid,
        name: Option<&str>,
        description: Option<&str>,
        path: Option<&str>,
        method: Option<&str>,
        content: Option<&serde_json::Value>,
        tags: Option<&serde_json::Value>,
    ) -> StoreResult<Option<CloudFixture>> {
        Ok(None)
    }

    #[allow(unused_variables)]
    async fn delete_cloud_fixture(&self, id: Uuid) -> StoreResult<()> {
        Ok(())
    }

    #[allow(unused_variables)]
    async fn create_hosted_mock(
        &self,
        org_id: Uuid,
        project_id: Option<Uuid>,
        name: &str,
        slug: &str,
        description: Option<&str>,
        config_json: serde_json::Value,
        openapi_spec_url: Option<&str>,
        region: Option<&str>,
    ) -> StoreResult<HostedMock> {
        Err(StoreError::NotFound)
    }

    #[allow(unused_variables)]
    async fn find_hosted_mock_by_id(&self, id: Uuid) -> StoreResult<Option<HostedMock>> {
        Ok(None)
    }

    #[allow(unused_variables)]
    async fn find_hosted_mock_by_slug(
        &self,
        org_id: Uuid,
        slug: &str,
    ) -> StoreResult<Option<HostedMock>> {
        Ok(None)
    }

    #[allow(unused_variables)]
    async fn list_hosted_mocks_by_org(&self, org_id: Uuid) -> StoreResult<Vec<HostedMock>> {
        Ok(Vec::new())
    }

    #[allow(unused_variables)]
    async fn update_hosted_mock_status(
        &self,
        id: Uuid,
        status: DeploymentStatus,
        error_message: Option<&str>,
    ) -> StoreResult<()> {
        Ok(())
    }

    #[allow(unused_variables)]
    async fn update_hosted_mock_urls(
        &self,
        id: Uuid,
        deployment_url: Option<&str>,
        internal_url: Option<&str>,
    ) -> StoreResult<()> {
        Ok(())
    }

    #[allow(unused_variables)]
    async fn update_hosted_mock_health(
        &self,
        id: Uuid,
        health_status: HealthStatus,
        health_check_url: Option<&str>,
    ) -> StoreResult<()> {
        Ok(())
    }

    #[allow(unused_variables)]
    async fn delete_hosted_mock(&self, id: Uuid) -> StoreResult<()> {
        Ok(())
    }

    #[allow(unused_variables)]
    async fn subscribe_waitlist(
        &self,
        email: &str,
        source: &str,
    ) -> StoreResult<WaitlistSubscriber> {
        Err(StoreError::NotFound)
    }

    #[allow(unused_variables)]
    async fn unsubscribe_waitlist_by_token(&self, token: Uuid) -> StoreResult<bool> {
        Ok(false)
    }

    #[allow(unused_variables)]
    async fn get_or_create_current_usage_counter(&self, org_id: Uuid) -> StoreResult<UsageCounter> {
        Err(StoreError::NotFound)
    }

    #[allow(unused_variables)]
    async fn list_usage_counters_by_org(&self, org_id: Uuid) -> StoreResult<Vec<UsageCounter>> {
        Ok(Vec::new())
    }

    #[allow(unused_variables)]
    async fn find_sso_config_by_org(&self, org_id: Uuid) -> StoreResult<Option<SSOConfiguration>> {
        Ok(None)
    }

    #[allow(unused_variables)]
    async fn upsert_sso_config(
        &self,
        org_id: Uuid,
        provider: SSOProvider,
        saml_entity_id: Option<&str>,
        saml_sso_url: Option<&str>,
        saml_slo_url: Option<&str>,
        saml_x509_cert: Option<&str>,
        saml_name_id_format: Option<&str>,
        attribute_mapping: Option<serde_json::Value>,
        require_signed_assertions: bool,
        require_signed_responses: bool,
        allow_unsolicited_responses: bool,
    ) -> StoreResult<SSOConfiguration> {
        Err(StoreError::NotFound)
    }

    #[allow(unused_variables)]
    async fn enable_sso_config(&self, org_id: Uuid) -> StoreResult<()> {
        Ok(())
    }

    #[allow(unused_variables)]
    async fn disable_sso_config(&self, org_id: Uuid) -> StoreResult<()> {
        Ok(())
    }

    #[allow(unused_variables)]
    async fn delete_sso_config(&self, org_id: Uuid) -> StoreResult<()> {
        Ok(())
    }

    #[allow(unused_variables)]
    async fn is_saml_assertion_used(&self, assertion_id: &str, org_id: Uuid) -> StoreResult<bool> {
        Ok(false)
    }

    #[allow(unused_variables)]
    async fn record_saml_assertion_used(
        &self,
        assertion_id: &str,
        org_id: Uuid,
        user_id: Option<Uuid>,
        name_id: Option<&str>,
        issued_at: DateTime<Utc>,
        expires_at: DateTime<Utc>,
    ) -> StoreResult<SAMLAssertionId> {
        Err(StoreError::NotFound)
    }

    #[allow(unused_variables)]
    async fn create_org_template(
        &self,
        org_id: Uuid,
        name: &str,
        description: Option<&str>,
        blueprint_config: Option<serde_json::Value>,
        security_baseline: Option<serde_json::Value>,
        created_by: Uuid,
        is_default: bool,
    ) -> StoreResult<OrgTemplate> {
        Err(StoreError::NotFound)
    }

    #[allow(unused_variables)]
    async fn find_org_template_by_id(&self, id: Uuid) -> StoreResult<Option<OrgTemplate>> {
        Ok(None)
    }

    #[allow(unused_variables)]
    async fn list_org_templates_by_org(&self, org_id: Uuid) -> StoreResult<Vec<OrgTemplate>> {
        Ok(Vec::new())
    }

    #[allow(unused_variables)]
    async fn update_org_template(
        &self,
        template: &OrgTemplate,
        name: Option<&str>,
        description: Option<&str>,
        blueprint_config: Option<serde_json::Value>,
        security_baseline: Option<serde_json::Value>,
        is_default: Option<bool>,
    ) -> StoreResult<OrgTemplate> {
        Err(StoreError::NotFound)
    }

    #[allow(unused_variables)]
    async fn delete_org_template(&self, id: Uuid) -> StoreResult<()> {
        Ok(())
    }

    #[allow(unused_variables)]
    async fn create_template(
        &self,
        org_id: Option<Uuid>,
        name: &str,
        slug: &str,
        description: &str,
        author_id: Uuid,
        version: &str,
        category: TemplateCategory,
        content_json: serde_json::Value,
    ) -> StoreResult<Template> {
        Err(StoreError::NotFound)
    }

    #[allow(unused_variables)]
    async fn find_template_by_name_version(
        &self,
        name: &str,
        version: &str,
    ) -> StoreResult<Option<Template>> {
        Ok(None)
    }

    #[allow(unused_variables)]
    async fn list_templates_by_org(&self, org_id: Uuid) -> StoreResult<Vec<Template>> {
        Ok(Vec::new())
    }

    #[allow(unused_variables)]
    async fn search_templates(
        &self,
        query: Option<&str>,
        category: Option<&str>,
        tags: &[String],
        org_id: Option<Uuid>,
        limit: i64,
        offset: i64,
    ) -> StoreResult<Vec<Template>> {
        Ok(Vec::new())
    }

    #[allow(unused_variables)]
    async fn count_search_templates(
        &self,
        query: Option<&str>,
        category: Option<&str>,
        tags: &[String],
        org_id: Option<Uuid>,
    ) -> StoreResult<i64> {
        Ok(0)
    }

    #[allow(unused_variables)]
    async fn create_scenario(
        &self,
        org_id: Option<Uuid>,
        name: &str,
        slug: &str,
        description: &str,
        author_id: Uuid,
        current_version: &str,
        category: &str,
        license: &str,
        manifest_json: serde_json::Value,
    ) -> StoreResult<Scenario> {
        Err(StoreError::NotFound)
    }

    #[allow(unused_variables)]
    async fn find_scenario_by_name(&self, name: &str) -> StoreResult<Option<Scenario>> {
        Ok(None)
    }

    #[allow(unused_variables)]
    async fn list_scenarios_by_org(&self, org_id: Uuid) -> StoreResult<Vec<Scenario>> {
        Ok(Vec::new())
    }

    #[allow(unused_variables)]
    async fn search_scenarios(
        &self,
        query: Option<&str>,
        category: Option<&str>,
        tags: &[String],
        org_id: Option<Uuid>,
        sort: &str,
        limit: i64,
        offset: i64,
    ) -> StoreResult<Vec<Scenario>> {
        Ok(Vec::new())
    }

    #[allow(unused_variables)]
    async fn count_search_scenarios(
        &self,
        query: Option<&str>,
        category: Option<&str>,
        tags: &[String],
        org_id: Option<Uuid>,
    ) -> StoreResult<i64> {
        Ok(0)
    }

    #[allow(unused_variables)]
    async fn search_plugins(
        &self,
        query: Option<&str>,
        category: Option<&str>,
        tags: &[String],
        sort_by: &str,
        limit: i64,
        offset: i64,
    ) -> StoreResult<Vec<Plugin>> {
        Ok(Vec::new())
    }

    #[allow(unused_variables)]
    async fn count_search_plugins(
        &self,
        query: Option<&str>,
        category: Option<&str>,
        tags: &[String],
    ) -> StoreResult<i64> {
        Ok(0)
    }

    #[allow(unused_variables)]
    async fn find_plugin_by_name(&self, name: &str) -> StoreResult<Option<Plugin>> {
        Ok(None)
    }

    #[allow(unused_variables)]
    async fn get_plugin_tags(&self, plugin_id: Uuid) -> StoreResult<Vec<String>> {
        Ok(Vec::new())
    }

    #[allow(unused_variables)]
    async fn create_plugin(
        &self,
        name: &str,
        description: &str,
        version: &str,
        category: &str,
        license: &str,
        repository: Option<&str>,
        homepage: Option<&str>,
        author_id: Uuid,
    ) -> StoreResult<Plugin> {
        Err(StoreError::NotFound)
    }

    #[allow(unused_variables)]
    async fn list_plugin_versions(&self, plugin_id: Uuid) -> StoreResult<Vec<PluginVersion>> {
        Ok(Vec::new())
    }

    #[allow(unused_variables)]
    async fn find_plugin_version(
        &self,
        plugin_id: Uuid,
        version: &str,
    ) -> StoreResult<Option<PluginVersion>> {
        Ok(None)
    }

    #[allow(unused_variables)]
    async fn create_plugin_version(
        &self,
        plugin_id: Uuid,
        version: &str,
        download_url: &str,
        checksum: &str,
        file_size: i64,
        min_mockforge_version: Option<&str>,
    ) -> StoreResult<PluginVersion> {
        Err(StoreError::NotFound)
    }

    #[allow(unused_variables)]
    async fn yank_plugin_version(&self, version_id: Uuid) -> StoreResult<()> {
        Ok(())
    }

    #[allow(unused_variables)]
    async fn get_plugin_version_dependencies(
        &self,
        version_id: Uuid,
    ) -> StoreResult<std::collections::HashMap<String, String>> {
        Ok(std::collections::HashMap::new())
    }

    #[allow(unused_variables)]
    async fn add_plugin_version_dependency(
        &self,
        version_id: Uuid,
        plugin_name: &str,
        version_req: &str,
    ) -> StoreResult<()> {
        Ok(())
    }

    #[allow(unused_variables)]
    async fn get_plugin_reviews(
        &self,
        plugin_id: Uuid,
        limit: i64,
        offset: i64,
    ) -> StoreResult<Vec<Review>> {
        Ok(Vec::new())
    }

    #[allow(unused_variables)]
    async fn count_plugin_reviews(&self, plugin_id: Uuid) -> StoreResult<i64> {
        Ok(0)
    }

    #[allow(unused_variables)]
    async fn create_plugin_review(
        &self,
        plugin_id: Uuid,
        user_id: Uuid,
        version: &str,
        rating: i16,
        title: Option<&str>,
        comment: &str,
    ) -> StoreResult<Review> {
        Err(StoreError::NotFound)
    }

    #[allow(unused_variables)]
    async fn get_plugin_review_stats(&self, plugin_id: Uuid) -> StoreResult<(f64, i64)> {
        Ok((0.0, 0))
    }

    #[allow(unused_variables)]
    async fn get_plugin_review_distribution(
        &self,
        plugin_id: Uuid,
    ) -> StoreResult<std::collections::HashMap<i16, i64>> {
        Ok(std::collections::HashMap::new())
    }

    #[allow(unused_variables)]
    async fn find_existing_plugin_review(
        &self,
        plugin_id: Uuid,
        user_id: Uuid,
    ) -> StoreResult<Option<Uuid>> {
        Ok(None)
    }

    #[allow(unused_variables)]
    async fn update_plugin_rating_stats(
        &self,
        plugin_id: Uuid,
        avg: f64,
        count: i32,
    ) -> StoreResult<()> {
        Ok(())
    }

    #[allow(unused_variables)]
    async fn increment_plugin_review_vote(
        &self,
        plugin_id: Uuid,
        review_id: Uuid,
        helpful: bool,
    ) -> StoreResult<()> {
        Ok(())
    }

    #[allow(unused_variables)]
    async fn get_user_public_info(&self, user_id: Uuid) -> StoreResult<Option<(String, String)>> {
        Ok(None)
    }

    #[allow(unused_variables)]
    async fn get_template_reviews(
        &self,
        template_id: Uuid,
        limit: i64,
        offset: i64,
    ) -> StoreResult<Vec<TemplateReview>> {
        Ok(Vec::new())
    }

    #[allow(unused_variables)]
    async fn count_template_reviews(&self, template_id: Uuid) -> StoreResult<i64> {
        Ok(0)
    }

    #[allow(unused_variables)]
    async fn create_template_review(
        &self,
        template_id: Uuid,
        reviewer_id: Uuid,
        rating: i32,
        title: Option<&str>,
        comment: &str,
    ) -> StoreResult<TemplateReview> {
        Err(StoreError::NotFound)
    }

    #[allow(unused_variables)]
    async fn update_template_review_stats(&self, template_id: Uuid) -> StoreResult<()> {
        Ok(())
    }

    #[allow(unused_variables)]
    async fn find_existing_template_review(
        &self,
        template_id: Uuid,
        reviewer_id: Uuid,
    ) -> StoreResult<Option<Uuid>> {
        Ok(None)
    }

    #[allow(unused_variables)]
    async fn get_scenario_reviews(
        &self,
        scenario_id: Uuid,
        limit: i64,
        offset: i64,
    ) -> StoreResult<Vec<ScenarioReview>> {
        Ok(Vec::new())
    }

    #[allow(unused_variables)]
    async fn count_scenario_reviews(&self, scenario_id: Uuid) -> StoreResult<i64> {
        Ok(0)
    }

    #[allow(unused_variables)]
    async fn create_scenario_review(
        &self,
        scenario_id: Uuid,
        reviewer_id: Uuid,
        rating: i32,
        title: Option<&str>,
        comment: &str,
    ) -> StoreResult<ScenarioReview> {
        Err(StoreError::NotFound)
    }

    #[allow(unused_variables)]
    async fn update_scenario_review_stats(&self, scenario_id: Uuid) -> StoreResult<()> {
        Ok(())
    }

    #[allow(unused_variables)]
    async fn find_existing_scenario_review(
        &self,
        scenario_id: Uuid,
        reviewer_id: Uuid,
    ) -> StoreResult<Option<Uuid>> {
        Ok(None)
    }

    #[allow(unused_variables)]
    async fn get_admin_analytics_snapshot(&self) -> StoreResult<AdminAnalyticsSnapshot> {
        Ok(AdminAnalyticsSnapshot {
            total_users: 0,
            verified_users: 0,
            auth_providers: Vec::new(),
            new_users_7d: 0,
            new_users_30d: 0,
            total_orgs: 0,
            plan_distribution: Vec::new(),
            active_subs: 0,
            trial_orgs: 0,
            total_requests: None,
            total_storage: None,
            total_ai_tokens: None,
            top_orgs: Vec::new(),
            hosted_mocks_count: 0,
            hosted_mocks_orgs: 0,
            hosted_mocks_30d: 0,
            plugins_count: 0,
            plugins_orgs: 0,
            plugins_30d: 0,
            templates_count: 0,
            templates_orgs: 0,
            templates_30d: 0,
            scenarios_count: 0,
            scenarios_orgs: 0,
            scenarios_30d: 0,
            api_tokens_count: 0,
            api_tokens_orgs: 0,
            api_tokens_30d: 0,
            user_growth_30d: Vec::new(),
            org_growth_30d: Vec::new(),
            logins_24h: 0,
            logins_7d: 0,
            api_requests_24h: 0,
            api_requests_7d: 0,
        })
    }

    #[allow(unused_variables)]
    async fn get_conversion_funnel_snapshot(
        &self,
        interval: &str,
    ) -> StoreResult<ConversionFunnelSnapshot> {
        Ok(ConversionFunnelSnapshot {
            signups: 0,
            verified: 0,
            logged_in: 0,
            org_created: 0,
            feature_users: 0,
            checkout_initiated: 0,
            paid_subscribers: 0,
            time_to_convert_days: None,
        })
    }

    #[allow(unused_variables)]
    async fn list_user_settings_raw(&self, user_id: Uuid) -> StoreResult<Vec<UserSettingRow>> {
        Ok(Vec::new())
    }

    #[allow(unused_variables)]
    async fn list_user_api_tokens(&self, user_id: Uuid) -> StoreResult<Vec<ApiToken>> {
        Ok(Vec::new())
    }

    #[allow(unused_variables)]
    async fn get_org_membership_role(
        &self,
        org_id: Uuid,
        user_id: Uuid,
    ) -> StoreResult<Option<String>> {
        Ok(None)
    }

    #[allow(unused_variables)]
    async fn list_org_settings_raw(&self, org_id: Uuid) -> StoreResult<Vec<OrgSettingRow>> {
        Ok(Vec::new())
    }

    #[allow(unused_variables)]
    async fn list_org_projects_raw(&self, org_id: Uuid) -> StoreResult<Vec<ProjectRow>> {
        Ok(Vec::new())
    }

    #[allow(unused_variables)]
    async fn list_org_subscriptions_raw(&self, org_id: Uuid) -> StoreResult<Vec<SubscriptionRow>> {
        Ok(Vec::new())
    }

    #[allow(unused_variables)]
    async fn list_org_hosted_mocks_raw(&self, org_id: Uuid) -> StoreResult<Vec<HostedMock>> {
        Ok(Vec::new())
    }

    #[allow(unused_variables)]
    async fn delete_user_data_cascade(&self, user_id: Uuid) -> StoreResult<usize> {
        Ok(0)
    }
}
