[package]
name = "enhanced-mock-data-generation-example"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "enhanced-mock-data-generation"
path = "main.rs"

[dependencies]
mockforge-data = { path = "../../crates/mockforge-data" }
tokio = { version = "1.0", features = ["full"] }
serde_json = "1.0"
